Repository Programmers-Coach-Coach/Coach-Coach-server, pull requests merged in 2024-08, with the labels that each got.

#38 feat : date entity updatedAt 추가, securityconfig 수정
  src/main/java/site/coach_coach/coach_coach_server/common/domain/DateEntity.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/resources/db/migration/V1__init.sql
Labels: feature

#41 chore(config) : SecurityConfig에 Cors 설정 추가
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/test/java/site/coach_coach/coach_coach_server/config/SecurityConfigTest.java
Labels: chore

#43 refactor : Cors loacal 주소 추가
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/test/java/site/coach_coach/coach_coach_server/config/SecurityConfigTest.java
Labels: refactor

#47 chore : local의 모든 포트에 대해 허용
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
Labels: chore

#49 chore : 프론트엔드 개발 도메인 CORS 승인
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
Labels: chore

#51 feat : refresh_tokens table 추가
  src/main/resources/db/migration/V2__add_new_table.sql
Labels: refactor

#52 feat(user) : 로그인 api 구현 및 refresh token 추가
  build.gradle
  docker-compose.yml
  src/main/java/site/coach_coach/coach_coach_server/CoachCoachServerApplication.java
  src/main/java/site/coach_coach/coach_coach_server/auth/exception/ExpiredTokenException.java
  src/main/java/site/coach_coach/coach_coach_server/auth/exception/InvalidTokenException.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtProperties.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/domain/RefreshToken.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/dto/TokenDto.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/RefreshTokenService.java
  src/main/java/site/coach_coach/coach_coach_server/auth/userdetails/CustomUserDetails.java
  src/main/java/site/coach_coach/coach_coach_server/auth/userdetails/CustomUserDetailsService.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/UserNotFoundException.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/Enum.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/EnumValidator.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/LoginRequest.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/SignUpRequest.java
  src/main/java/site/coach_coach/coach_coach_server/user/exception/UserNotFoundException.java
  src/main/java/site/coach_coach/coach_coach_server/user/repository/UserRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/resources/db/migration/V2__add_new_table.sql
  src/main/resources/db/migration/V3__alter_refresh_tokens_table_column.sql
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/service/RefreshTokenServiceTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/dto/SignUpRequestTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/service/UserServiceTest.java
Labels: feature

#58 feat(user, token) : 인증 api 구현 및 토큰 재발급 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/domain/RefreshToken.java
  src/main/java/site/coach_coach/coach_coach_server/common/utils/AuthenticationUtil.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
Labels: feature

#62 feat(user) : logout api 구현
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/RefreshTokenService.java
  src/main/java/site/coach_coach/coach_coach_server/auth/userdetails/CustomUserDetails.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/config/ExceptionHandlerConfig.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/service/RefreshTokenServiceTest.java
Labels: feature

#66 refactor : DB 컬럼 변경 및 추가
  src/main/resources/db/migration/V4__modify_column_settings.sql
Labels: refactor

#69 refactor(user) : 토큰 재발급 api 추가 & refresh token 재발급 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenServiceTest.java
  src/test/java/site/coach_coach/coach_coach_server/config/SecurityConfigTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
Labels: refactor

#71 refactor : 로그아웃 로직 수정 및 에러 처리 수정
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/config/CustomAuthenticationEntryPoint.java
  src/main/java/site/coach_coach/coach_coach_server/config/ExceptionHandlerConfig.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
Labels: refactor

#74 chore(cd) : flyway 설정 수정
  docker-compose.yml
Labels: chore

#80 refactor : response 수정 및 인증 관련 코드 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/domain/RefreshToken.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/ErrorResponse.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/response/ErrorResponse.java
  src/main/java/site/coach_coach/coach_coach_server/common/response/SuccessResponse.java
  src/main/java/site/coach_coach/coach_coach_server/config/CustomAuthenticationEntryPoint.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/UserDto.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenServiceTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/dto/UserDtoTest.java
Labels: refactor

#81 refactor : 루틴 목록 조회 API 기능 분리
  src/main/java/site/coach_coach/coach_coach_server/coach/domain/Coach.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/matching/Dto/CheckMatchingDto.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListResponse.java
  src/main/java/site/coach_coach/coach_coach_server/routine/exception/NotMatchingException.java
  src/main/java/site/coach_coach/coach_coach_server/routine/services/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/exception/InvalidUserException.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/service/UserServiceTest.java
Labels: refactor

#83 feat : logging 설정 및 적용
  .gitignore
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: feature

#84 feature(routine) : 루틴 목록 관련 사용자 정보 조회 API 구현
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/UserInfoForRoutineList.java
  src/main/java/site/coach_coach/coach_coach_server/routine/services/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/user/exception/InvalidUserException.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
Labels: feature

#63 feat : 테스트 커버리지 Jacoco 적용
  .github/workflows/ci.yml
  build.gradle
  lombok.config
  src/main/java/site/coach_coach/coach_coach_server/config/ExceptionHandlerConfig.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/test/java/site/coach_coach/coach_coach_server/mainInfo/controller/MainInfoControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature

#92 feat(cookie) : cookie에 setDomain 속성 추가
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
Labels: feature

#88 feat(user) : 마이페이지 조회 api 구현
  src/main/java/site/coach_coach/coach_coach_server/sport/dto/InterestedSportDto.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/UserProfileResponse.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
Labels: feature

#94 refactor : cd 빌드 시 테스트 제외
  .github/workflows/cd.yml
Labels: refactor

#96 fix(cookie) : cookie 속성 변경
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
Labels: fix

#98 fix(cookie) : cookie settings에 domain 추가
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
Labels: fix

#100 fix(cookie) : 쿠키 sameSite 삭제
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
Labels: fix

#102 fix : cookie에 sameSite 추가
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
Labels: fix

#104 fix(cookie) : cookie domain 수정
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProvider.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
Labels: fix

#91 feat(sentry) : 서버 에러 센트리 이슈 관리
  build.gradle
  src/main/java/site/coach_coach/coach_coach_server/CoachCoachServerApplication.java
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/config/SentryConfiguration.java
Labels: feature

#109 feat(routine) : 루틴 삭제 API 구현
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/exception/NoExistRoutineException.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature

#113 refactor(maininfo) : service 로직 수정 및 네이밍 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/coach/util/CoachDtoBuilder.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/controller/MainInfoController.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/dto/MainInfoCoachDto.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/dto/MainInfoResponseDto.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/service/MainInfoService.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/service/MainService.java
  src/main/java/site/coach_coach/coach_coach_server/sport/dto/CoachingSportDto.java
  src/main/java/site/coach_coach/coach_coach_server/sport/dto/SportDto.java
  src/test/java/site/coach_coach/coach_coach_server/mainInfo/controller/MainInfoControllerTest.java
Labels: refactor

#118 fix(user) : 마이페이지 조회, 수정 api url 변경
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
Labels: fix

#114 feat(coachDetail) : 코치 상세 정보 조회 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachDetailDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundCoachException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/review/dto/ReviewDto.java
  src/main/java/site/coach_coach/coach_coach_server/sport/dto/InterestedSportDto.java
Labels: feature

#121 refactor : transactional annotaion 변경
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
Labels: refactor

#123 chore : flyway v5 추가
  src/main/resources/db/migration/V5__modify_column_setting.sql
Labels: chore

#125 fix(coach) : coachRepository param 추가
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
Labels: fix

#142 refactor : jacoco 설정 임시 수정
  build.gradle
Labels: refactor

#139 feat(notification) : 알림 추가 로직 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/notification/constants/NotificationMessage.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
Labels: feature

#135 fix(sentry) : ExceptionHandler sentry 설정 변경
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/JwtExceptionFilter.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
Labels: fix

#144 refactor : matching entity 연관관계 매핑 수정
  src/main/java/site/coach_coach/coach_coach_server/matching/domain/Matching.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: refactor

#148 chore(flyway) : flyway v6 추가
  src/main/resources/db/migration/V6__modify_column_settings.sql
Labels: chore

#137 refactor(coach) : 전체 리스트 반환 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/sport/repository/CoachingSportRepository.java
Labels: refactor

#157 chore(flyway) : config파일 & V7 sql 파일 추가
  src/main/java/site/coach_coach/coach_coach_server/config/FlywayConfig.java
  src/main/resources/db/migration/V7__modify_column_setting.sql
Labels: chore

#163 feat(user) : 사용자 인증 정보 조회 api 구현
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/AuthResponse.java
  src/main/java/site/coach_coach/coach_coach_server/user/repository/UserRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
Labels: feature

#158 feat : 카테고리 추가 API 구현
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CreateCategoryRequest.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CreateCategoryResponse.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/CreateRoutineRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/validation/RoutineName.java
  src/main/java/site/coach_coach/coach_coach_server/routine/validation/RoutineNameValidator.java
  src/main/resources/db/migration/V6__modify_column_settings.sql
Labels: feature

#160 refactor(coach) : 코치 정보 조회 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/review/domain/Review.java
  src/main/java/site/coach_coach/coach_coach_server/sport/domain/CoachingSport.java
Labels: refactor

#155 feat(coach) : Contact coach API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/DuplicateContactException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/matching/domain/Matching.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
Labels: feature

#162 feat(coach) : 매칭 회원 등록 API 구현
  scripts/start.sh
  scripts/stop.sh
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/AlreadyMatchedException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundMatchingException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/matching/domain/Matching.java
Labels: feature

#166 chore(flyway) : flyway v8 추가
  src/main/resources/db/migration/V8__CASCADE_modify_table_setting.sql
Labels: chore

#169 fix(flyway) : flyway v8
  src/main/resources/db/migration/V8__CASCADE_modify_table_setting.sql
Labels: fix

#170 refactor(user) : 알림 관련 로직과 인증 상태 정보 로직 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/notification/repository/NotificationRepository.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
  src/main/java/site/coach_coach/coach_coach_server/user/repository/UserRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
Labels: refactor

#130 feat(coach) : 코치 등록/수정 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/domain/Coach.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachRequest.java
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/sport/domain/CoachingSport.java
  src/main/java/site/coach_coach/coach_coach_server/sport/repository/CoachingSportRepository.java
Labels: feature

#172 feat(category) : 카테고리 삭제 API 구현
  scripts/start.sh
  scripts/stop.sh
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/exception/NotFoundCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/domain/CompletedCategory.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/domain/UserRecord.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
Labels: feature

#186 chore(db) : flyway v9 파일 작성
  src/main/resources/db/migration/V9__modify_tables_and_columns.sql
Labels: chore

#182 refactor(coach) : Contact Coach API statuscode
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
Labels: refactor

#181 refactor(coach) : 코치 정보 등록/수정 API SportName
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
Labels: refactor

#176 feat(coach) : 관심 코치(좋아요) 등록 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
Labels: feature

#178 feat(coach) : 관심 코치(좋아요) 취소 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/like/repository/UserCoachLikeRepository.java
  src/main/resources/db/migration/V6__modify_column_setting.sql
Labels: feature

#185 feat(coach) : 문의/매칭 회원 삭제 API구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/resources/db/migration/V6__modify_column_setting.sql
Labels: feature

#190 feat(record) : 신체 정보 입력 api 구현
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/response/SuccessIdResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/domain/UserRecord.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordCreateRequest.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/exception/DuplicateRecordException.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: feature

#192 feat(record) : 신체 정보 수정 api 구현
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/domain/UserRecord.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordUpdateRequest.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: feature

#194 feat(coach) : 문의/매칭 회원 조회 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/MatchingUserResponseDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
Labels: feature

#196 feat(category) : 카테고리 수행 완료 및 완료 취소 API
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/controller/CompletedCategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/domain/CompletedCategory.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/exception/DuplicateCompletedCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/exception/NotFoundCompletedCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineForListDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature

#197 feat(user) : 문의/매칭 코치 조회 기능 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/MatchingCoachResponseDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
Labels: feature

#199 feat(action) : 운동 추가 API 구현
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/CreateActionRequest.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
Labels: feature

#202 feat(record) : 나의 운동 기록 조회 API 구현
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/domain/CompletedCategory.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/RecordResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
  src/test/java/site/coach_coach/coach_coach_server/auth/jwt/TokenProviderTest.java
Labels: feature

#200 feat(action) : 운동 삭제 API 구현
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/exception/NotFoundActionException.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/exception/DuplicateCompletedCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature

#203 feat(coach) : 리뷰 등록 API 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/ReviewRequestDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/DuplicateReviewException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/review/repository/ReviewRepository.java
Labels: feature

#205 refactor(coach) : 코치 상세 정보 조회 시 coachID 추가
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachDetailDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
Labels: refactor

#207 refactor : 루틴 관련 항목 삭제 검증 로직 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: refactor

#209 refactor(routine) : 루틴 관련 항목 추가 기능 검증 로직 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
Labels: refactor

#210 feat(routine) : 루틴 수정 API 구현
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/UpdateRoutineInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: feature

#213 feat(category) : 카테고리 수정 API 구현
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/UpdateCategoryInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
Labels: feature

#215 feat(actioin) : 운동 정보 수정 API
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/UpdateActionInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
Labels: feature

#220 refactor : 메서드명 일치화 및 주석 제거
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: refactor

#221 refactor(record) : Join을 사용하도록 기록 조회 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/domain/UserRecord.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#225 refactor(routine) : 루틴목록 조회 비즈니스 로직 리팩토링 및 오타 수정
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: refactor

#226 feat(record) : 신체 정보 차트 api 구현
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/BodyInfoChartResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: feature

#228 feat(routine) : routine Entity에 userId와 coachId 매핑
  src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
  src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: feature

#229 refactor(category) : 카테고리 완료 로직 보완 및 중복되는 검증 로직 제거
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/controller/CompletedCategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
Labels: refactor

#231 feat(record) : 기록 디테일 조회 api 구현
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CategoryDto.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/dto/CompletedCategoryDto.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/RecordsDto.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordDetailResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: feature

#232 chore(flyway) : flyway V10 추가
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/db/migration/V10__modify_columns.sql
Labels: chore

#235 refactor(record) : 신체 정보 수정 api response 수정
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
Labels: refactor

#238 refactor(record) : 차트 api - 0이 아닌 경우만 결과에 포함하도록 변경
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
Labels: refactor

#239 refactor(exception) : Not Found 관련 에러 처리 refactoring
  src/main/java/site/coach_coach/coach_coach_server/action/exception/NotFoundActionException.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/exception/NotFoundCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundCoachException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundMatchingException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundPageException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/NotFoundSportException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/NotFoundException.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/UserNotFoundException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/exception/NotFoundCompletedCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/controller/MainInfoController.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/exception/NoExistRoutineException.java
  src/main/java/site/coach_coach/coach_coach_server/routine/exception/NotMatchingException.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/sport/validation/SportsValidator.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: refactor

#242 refactor(record) : 쿼리 성능을 위한 CASE문 사용
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
Labels: refactor

#244 chore(flyway) : flyway v11 추가
  src/main/resources/db/migration/V11_modify_column_setting.sql
Labels: chore

#246 feat(user) : Auth response 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/AuthResponse.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
Labels: feature

#250 refactor(record) : response에 record Id 추가
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordDetailResponse.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#251 chore : Flyway V12 작성
  src/main/resources/db/migration/V12_modify_columns.sql
Labels: chore

#255 refactor : V11, V12 SQL 파일 이름 수정
  src/main/resources/db/migration/V11__modify_column_setting.sql
  src/main/resources/db/migration/V12__modify_columns.sql
Labels: refactor

#252 refactor(exception) : duplicate 관련 예외 처리 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/AlreadyMatchedException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/DuplicateContactException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/DuplicateReviewException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/exception/InvalidQueryParameterException.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/DuplicateValueException.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ValidBoolean.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ValidBooleanValidator.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/exception/DuplicateCompletedCategoryException.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/exception/DuplicateRecordException.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#256 refactor(action) : countOrMinutes 데이터 분리
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/CreateActionRequest.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/UpdateActionInfoRequest.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: refactor

#262 refactor(category) : 자정마다 is_completed 값 초기화 기능 추가
  src/main/java/site/coach_coach/coach_coach_server/CoachCoachServerApplication.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
Labels: refactor

#263 refactor(coach) : 코치 본인에 대한 요청 처리
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/SelfRequestNotAllowedException.java
Labels: refactor

#265 refactor(coach) : 코치 상세 정보 조회 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachDetailDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
Labels: refactor

#267 refactor(coach) : 코치 전체 리스트 조회 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/sport/repository/SportRepository.java
Labels: refactor

#273 refactor : Change tinytext to varchar
  src/main/java/site/coach_coach/coach_coach_server/coach/domain/Coach.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachRequest.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/ReviewRequestDto.java
  src/main/java/site/coach_coach/coach_coach_server/review/domain/Review.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/UserProfileRequest.java
Labels: refactor

#275 refactor(notification) : 문의 수락 시 알림 메시지 추가
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/domain/RelationFunctionEnum.java
  src/main/java/site/coach_coach/coach_coach_server/notification/constants/NotificationMessage.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
Labels: refactor

#272 refactor(category) : 카테고리 완료 메서드 및 카테고리 Entity 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
Labels: refactor

#277 refactor(coach) : pathvariable name 추가
  scripts/start.sh
  scripts/stop.sh
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/notification/controller/NotificationController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
Labels: refactor

#281 refactor : flyway v14 파일 생성 및 회원 가입 시 isCoach 값 추가
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/resources/db/migration/V14__modify_tinyint.sql
Labels: refactor

#282 feat(coach) : 리뷰 수정 기능 구현 및 등록 기능 개선
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
  src/main/java/site/coach_coach/coach_coach_server/review/domain/Review.java
  src/main/java/site/coach_coach/coach_coach_server/review/dto/ReviewDto.java
Labels: feature

#285 refactor(action) : 운동 Entity 검증 어노테이션 수정
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
Labels: refactor

#283 feat(coach) : 리뷰 삭제 기능 구현
  scripts/start.sh
  scripts/stop.sh
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/SuccessMessage.java
  src/main/java/site/coach_coach/coach_coach_server/review/repository/ReviewRepository.java
Labels: feature

#287 refactor(chore) : 배포된 서버 실행 CLI 수정
  scripts/start.sh
Labels: chore

#289 refactor(mainInfo) : Refactor maininfo api
  src/main/java/site/coach_coach/coach_coach_server/like/repository/UserCoachLikeRepository.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/controller/MainInfoController.java
  src/main/java/site/coach_coach/coach_coach_server/maininfo/service/MainInfoService.java
Labels: refactor

#279 feat(user) : 회원 탈퇴 api 구현
  src/main/java/site/coach_coach/coach_coach_server/auth/jwt/service/TokenService.java
  src/main/java/site/coach_coach/coach_coach_server/review/domain/Review.java
  src/main/java/site/coach_coach/coach_coach_server/review/dto/ReviewDto.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/repository/UserRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/resources/db/migration/V15__reviews_user_id_null.sql
Labels: feature

#293 fix : review 테이블에 user_id default null 추가
  src/main/resources/db/migration/V15__reviews_user_id_null.sql
Labels: fix

#297 refactor : 배포되는 서버 파일명 변경
  scripts/start.sh
  scripts/stop.sh
Labels: refactor

#295 refactor(user) : user 회원 정보 오류 시 status code 400으로 수정
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
Labels: refactor

#306 refactor(notification) : 매칭 신청 시 알림 메시지 수정
  src/main/java/site/coach_coach/coach_coach_server/notification/constants/NotificationMessage.java
Labels: refactor

#307 refactor(category) : 루틴이 삭제되더라도 완료한 카테고리 기록 미삭제
  src/main/java/site/coach_coach/coach_coach_server/action/repository/ActionRepository.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/RecordsDto.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#311 refactor : 카테고리 완료 상태 초기화 로직 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
Labels: refactor

#303 refactor : V16(coachId cascade) & 매칭 삭제/거절에 대한 알림 추가
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/domain/RelationFunctionEnum.java
  src/main/java/site/coach_coach/coach_coach_server/notification/constants/NotificationMessage.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
  src/main/resources/db/migration/V16__add_coach_id_cascade.sql
Labels: chore

#312 fix(userRecord) : user record 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/RecordsDto.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: fix

#315 refactor(coach) : 코치 상세 정보 조회 isMatched 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/matching/repository/MatchingRepository.java
Labels: refactor

#318 refactor(coach) : 코치 리스트 조회 리뷰순 정렬 수정
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
Labels: refactor

#316 refactor(category) : 카테고리에 isDeleted 추가 및 카테고리 삭제 로직 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/action/repository/ActionRepository.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineResponse.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/resources/db/migration/V17__add_is_deleted_column.sql
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: refactor
