Repository Programmers-Coach-Coach/Coach-Coach-server, pull requests merged in 2024-07, with the labels that each got.

#4 chore : Naver Checkstyle 설정 추가 및 적용
  .editorconfig
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  config/formatter/naver-intellij-formatter.xml
Labels: chore

#6 chore : DB 및 Docker 초기 설정
  Dockerfile
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.properties
  mysql_coachcoach_ddl.sql
Labels: chore

#10 chore : CD 기능 구현
  .github/workflows/gradle.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
Labels: chore

#12 refactor : 줄바꿈 설정을 위한 파일 추가
  .gitattributes
Labels: refactor

#15 refactor : Docker 및 DB 설정 변경
  Dockerfile
  build.gradle
  docker-compose.yml
  mysql_coachcoach_ddl.sql
  src/main/resources/db/migration/V1_Initial_setup.sql
Labels: refactor

#18 refactor : EC2 서버 배포를 위한 커밋
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
Labels: refactor

#20 refactor : S3 업로드 작업을 CD 과정으로 변경
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: refactor

#22 refactor : cd.yml에 build 로직 추가
  .github/workflows/cd.yml
Labels: refactor

#24 refactor : CI/CD 작업 분리
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: refactor

#26 refactor : CI/CD 파일 코드 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: refactor

#33 Refactor : SQL 파일 및 구조 정리
  sql/V1__init.sql
  src/main/resources/db/migration/V1__init.sql
Labels: refactor

#35 Refactor : Docker compose volumes 업데이트
  docker-compose.yml
Labels: refactor

#27 feat(user) : 회원가입 API 구현
  .github/workflows/ci.yml
  build.gradle
  config/checkstyle/configuration_1_3.dtd
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  config/checkstyle/suppressions_1_1.dtd
  docker-compose.yml
  src/main/java/site/coach_coach/coach_coach_server/common/domain/DateEntity.java
  src/main/java/site/coach_coach/coach_coach_server/common/domain/GenderEnum.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/ErrorResponse.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/GlobalExceptionHandler.java
  src/main/java/site/coach_coach/coach_coach_server/common/exception/InvalidInputException.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/Enum.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/EnumValidator.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ValidBoolean.java
  src/main/java/site/coach_coach/coach_coach_server/common/validation/ValidBooleanValidator.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
  src/main/java/site/coach_coach/coach_coach_server/user/controller/UserController.java
  src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/SignupDto.java
  src/main/java/site/coach_coach/coach_coach_server/user/dto/UserDto.java
  src/main/java/site/coach_coach/coach_coach_server/user/exception/UserAlreadyExistException.java
  src/main/java/site/coach_coach/coach_coach_server/user/repository/UserRepository.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/java/site/coach_coach/coach_coach_server/user/validation/Nickname.java
  src/main/java/site/coach_coach/coach_coach_server/user/validation/NicknameValidator.java
  src/main/java/site/coach_coach/coach_coach_server/user/validation/Password.java
  src/main/java/site/coach_coach/coach_coach_server/user/validation/PasswordValidator.java
  src/test/java/site/coach_coach/coach_coach_server/user/controller/UserControllerTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/dto/SignupDtoTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/dto/UserDtoTest.java
  src/test/java/site/coach_coach/coach_coach_server/user/service/UserServiceTest.java
Labels: feature
