Repository Programmers-Coach-Coach/Coach-Coach-server, pull requests merged in 2024-11, with the labels that each got.

#328 refactor : 카테고리 테이블 삭제 및 관련 코드 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/action/controller/ActionController.java
  src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/ActionDto.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/CreateActionRequest.java
  src/main/java/site/coach_coach/coach_coach_server/action/dto/UpdateActionInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/action/repository/ActionRepository.java
  src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
  src/main/java/site/coach_coach/coach_coach_server/category/controller/CategoryController.java
  src/main/java/site/coach_coach/coach_coach_server/category/domain/Category.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CategoryDto.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CreateCategoryRequest.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/CreateCategoryResponse.java
  src/main/java/site/coach_coach/coach_coach_server/category/dto/UpdateCategoryInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/category/repository/CategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/category/service/CategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/common/Scheduler/SchedulerService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/dto/CompletedCategoryDto.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/repository/CompletedCategoryRepository.java
  src/main/java/site/coach_coach/coach_coach_server/completedcategory/service/CompletedCategoryService.java
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/controller/CompletedRoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/domain/CompletedRoutine.java
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/dto/CompletedRoutineDto.java
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/repository/CompletedRoutineRepository.java
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/service/CompletedRoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/repeatdate/converter/DayOfWeekSetConverter.java
  src/main/java/site/coach_coach/coach_coach_server/repeatdate/domain/RepeatDate.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/CreateRoutineRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineCreatorDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineForListDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineResponse.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/UpdateRoutineInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/domain/UserRecord.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/RecordsDto.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/repository/UserRecordRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
  src/main/resources/db/migration/V19__delete_categories_table.sql
  src/main/resources/logback-spring.xml
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature, refactor

#331 chore : v19 sql 파일 수정
  src/main/resources/db/migration/V19__delete_categories_table.sql
Labels: chore

#333 chore : flyway V19 syntax 에러 해결
  src/main/resources/db/migration/V19__delete_categories_table.sql
Labels: chore

#337 refactor : API 버전 수정 및 패키지명 컨벤션 적용
  src/main/java/site/coach_coach/coach_coach_server/common/scheduler/SchedulerService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/controller/RoutineController.java
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: refactor

#340 feat : 루틴의 반복일자 기능 구현
  src/main/java/site/coach_coach/coach_coach_server/routine/converter/DayOfWeekSetConverter.java
  src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/CreateRoutineRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/UpdateRoutineInfoRequest.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/resources/db/migration/V20__delete_repeat_dates_table.sql
  src/test/java/site/coach_coach/coach_coach_server/routine/controller/RoutineControllerTest.java
Labels: feature, chore

#343 feat(chatRoom): 채팅방 생성 로직, 조회, 채팅 메시지 조회 api 구현
  build.gradle
  src/main/java/site/coach_coach/coach_coach_server/chat/controller/ChatRoomController.java
  src/main/java/site/coach_coach/coach_coach_server/chat/domain/ChatMessage.java
  src/main/java/site/coach_coach/coach_coach_server/chat/domain/ChatRoom.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/mapper/ChatMessageMapper.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/mapper/ChatRoomMapper.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/request/ChatMessageRequest.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/request/ChatRoomRequest.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/response/ChatMessageResponse.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/response/CoachChatRoomsResponse.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/response/UserChatRoomsResponse.java
  src/main/java/site/coach_coach/coach_coach_server/chat/repository/ChatMessageRepository.java
  src/main/java/site/coach_coach/coach_coach_server/chat/repository/ChatRoomRepository.java
  src/main/java/site/coach_coach/coach_coach_server/chat/service/ChatRoomService.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/constants/ErrorMessage.java
  src/main/java/site/coach_coach/coach_coach_server/common/domain/RoleEnum.java
  src/main/java/site/coach_coach/coach_coach_server/config/MongoConfig.java
  src/main/java/site/coach_coach/coach_coach_server/config/WebSocketConfig.java
  src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListDto.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/resources/db/migration/V21__create_chatting_table.sql
Labels: feature

#347 refactor(mainInfo) :인기 코치 조회, 종목 조회 API 분리
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/PopularCoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/PopularCoachDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/PopularCoachService.java
  src/main/java/site/coach_coach/coach_coach_server/sport/controller/SportController.java
  src/main/java/site/coach_coach/coach_coach_server/sport/service/SportService.java
  src/test/java/site/coach_coach/coach_coach_server/mainInfo/controller/MainInfoControllerTest.java
Labels: refactor

#345 refactor(userRecord): 기록 디테일 조회 api 리팩토링
  src/main/java/site/coach_coach/coach_coach_server/completedroutine/repository/CompletedRoutineRepository.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#348 refactor(userRecord): 신체 정보 입력 및 수정 api 로직 수정
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#356 refactor(notification): 알림 api 로직 및 메시지 수정, 읽음 처리 기능 구현
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/common/domain/RelationFunctionEnum.java
  src/main/java/site/coach_coach/coach_coach_server/notification/constants/NotificationMessage.java
  src/main/java/site/coach_coach/coach_coach_server/notification/controller/NotificationController.java
  src/main/java/site/coach_coach/coach_coach_server/notification/domain/Notification.java
  src/main/java/site/coach_coach/coach_coach_server/notification/dto/NotificationListResponse.java
  src/main/java/site/coach_coach/coach_coach_server/notification/repository/NotificationRepository.java
  src/main/java/site/coach_coach/coach_coach_server/notification/service/NotificationService.java
  src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
  src/main/java/site/coach_coach/coach_coach_server/user/service/UserService.java
  src/main/resources/db/migration/V23__modify_notification_table.sql
Labels: feature, refactor

#357 refactor(coachList) : 코치 성별 필터 추가
  src/main/java/site/coach_coach/coach_coach_server/coach/controller/CoachController.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/CoachDetailDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/dto/PopularCoachDto.java
  src/main/java/site/coach_coach/coach_coach_server/coach/repository/CoachRepository.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/CoachService.java
  src/main/java/site/coach_coach/coach_coach_server/coach/service/PopularCoachService.java
  src/main/resources/db/migration/V22__add_total_user_count_column.sql
  src/main/resources/db/migration/V22_add_total_user_count_column.sql
Labels: feature, refactor

#360 refactor(userRecord): 기록 디테일 조회 response 변경
  src/main/java/site/coach_coach/coach_coach_server/userrecord/controller/UserRecordController.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/dto/UserRecordDetailV2Response.java
  src/main/java/site/coach_coach/coach_coach_server/userrecord/service/UserRecordService.java
Labels: refactor

#361 feat(chatMessage): websocket stomp를 이용한 실시간 채팅 기능 구현
  src/main/java/site/coach_coach/coach_coach_server/chat/controller/ChatMessageController.java
  src/main/java/site/coach_coach/coach_coach_server/chat/controller/ChatRoomController.java
  src/main/java/site/coach_coach/coach_coach_server/chat/domain/ChatMessage.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/mapper/ChatRoomMapper.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/request/ChatMessageRequest.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/response/CoachChatRoomsResponse.java
  src/main/java/site/coach_coach/coach_coach_server/chat/dto/response/UserChatRoomsResponse.java
  src/main/java/site/coach_coach/coach_coach_server/chat/repository/ChatMessageRepository.java
  src/main/java/site/coach_coach/coach_coach_server/chat/service/ChatMessageService.java
  src/main/java/site/coach_coach/coach_coach_server/chat/service/ChatRoomService.java
  src/main/java/site/coach_coach/coach_coach_server/config/SecurityConfig.java
Labels: feature
